### ISSUE TITLE
Ranking does not work.

### ISSUE THREAD

**Issue by bradyrenting** [poirierjm/fortniteDiscordBot#1]
Hello,

The bot does not gives a rank. The message output works perfectly though.

Console output:
`iBradyy
1.3
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 138, in on_message
    await client.remove_roles(message.author, roles)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 2946, in remove_roles
    new_roles.remove(role.id)
AttributeError: 'NoneType' object has no attribute 'id'
`

**Comment by poirierjm** [comment]
Hey,

Make sure the bot have admin right.
Also, have you created all roles from the list in the readme.md in your discord?

**Comment by bradyrenting** [comment]
Hey,

The bot does have administrator rights.
I made my own ranks and changed it. This is what it looks like:

https://pastebin.com/H3FjarZf

Brady

**Comment by poirierjm** [comment]
The error is occured when the bot is removing roles. Make sure all roles
assigned in the bots are the same as the one in your discord with no words
misspeled!

**Comment by chufy** [comment]
Hello im getting this error

```
MFC Chuf
3.65
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\enesc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 192, in on_message
    await client.send_message(message.channel, print_nextLvl(DIAMOND_B, DIAMOND_E, ratio))
  File "C:\Users\enesc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Users\enesc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Cannot send an empty message
```

But when i got this error bot says this on channel 
```
[4:28 PM] BOTPortakal: @MFC Chuf Your have been ranked Master
[4:28 PM] BOTPortakal: Next level: 3.65k/d  →  4.0k/d
```

Not assign any rank. And yes my bot have ALL permissions.

**Comment by chufy** [comment]
I solved every problem but bot doesn't get PS4 stats from fortnitetracker.com, why?

**Comment by poirierjm** [comment]
At line 39 replace:  link = 'https://api.fortnitetracker.com/v1/profile/pc/'
+ username
for:
link = 'https://api.fortnitetracker.com/v1/profile/psn/' + username
or¸
link = 'https://api.fortnitetracker.com/v1/profile/ps4/' + username Not
sure which one is it.
